version: "3.4"

services:

  api:
    build:
      dockerfile: Dockerfile.backend
      context: ./api
      target: development
    volumes:
      - ./api:/backend
      - /backend/node_modules
    # or npm run start:debug --> vscode debugger
    command: npm run start:dev
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/db
      NODE_ENV: development
      PORT: 3000
    env_file:
      - api/.env
    ports:
      - 3000:3000
      - 9229:9229

  frontend:
    build:  
      dockerfile: Dockerfile.frontend
      context: ./frontend
      target: development
    command: npm run start
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    ports:
      - 4200:4200
      - 49153:49153 # If port not manually exposed Angular hot reload doesn't trigger on Windows
    # maybe user networks instead?
    links:
      - api
  
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - 35000:5432
