FROM node:lts-slim AS development

WORKDIR /backend

COPY package*.json ./

RUN apt-get update && apt-get install procps -y

RUN npm install --legacy-peer-deps

COPY . .

RUN npm run build

EXPOSE 3000